[package]
name = "please"
version = "0.1.0"
edition = "2021"

[dependencies]
structopt = "0.3"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
arboard = "3.3.1"
dotenv = "0.15.0"
